### ISSUE TITLE
httpOnly and secure option not working please help!!!

### ISSUE THREAD

**Issue by hardikshah91** [microcipcip/cookie-universal#13]
below is the code how I am enabling cookies in actions.js in Nuxtjs project

```
await this.$axios
        .post(`/post_login/`, payload)
        .then(response => {
          if (response.status == 200) {
            this.$cookies.set('at', response.data.access_token, {
              opts: { httpOnly: true, secure: true }
            });
            this.$cookies.set('rt', response.data.refresh_token, {
              opts: { httpOnly: true, secure: true }
            });
            dispatch('GET_ME', { at: response.data.access_token });
            commit('SET_USER', response.data);
          }
        })
```
any one can help???
One more question is this secure and httpOnly option tick marked(enabled) on localhost too if above code written??

**Comment by microcipcip** [comment]
@hardikshah91 Your question is too generic. What is not working exactly? Your code looks right. Note though that while you can set httpOnly in localhost, **you probably won't be able to set the secure: true** because localhost cannot be set to HTTPS. A good solution would be to set it to false just for localhost development with a ternary like `secure: isDev ? false : true`. Also note that `httpOnly` means that you won't be able to read the cookie from the frontend.

Let me know if you have any other trouble.

**Comment by hardikshah91** [comment]
@microcipcip  
Yes, Correct. 
that httpOnly means that you won't be able to read/set the cookie from the frontend, only from the server.

But I'm able to read from the front end when I type `document.cookie` in browsers console.

**Comment by microcipcip** [comment]
@hardikshah91 If it is correctly set to httpOnly you should not be able to access it from js. I just tested my website and I can't read it from the console. Without example code I can't debug it. I don't understand your second question. Please be more specific and with code examples if necessary otherwise I cannot help you :)

**Comment by microcipcip** [comment]
I am closing this for now. If you still have the issue comment on this thread.
