### ISSUE TITLE
PATH not working

### ISSUE THREAD

**Issue by stephenjason89** [microcipcip/cookie-universal#134]
Hello @microcipcip ,
Thank you for the wonderful plugin.

I am currently doing 
```
import Cookie from 'cookie-universal'
const cookies = Cookie()
```

and setting a cookie with this options
```
{
                        path: '/',
                        maxAge: 60 * 60 * 24 * 90,
                        secure: true,
}
```

Everything is working except for the path.
Some of the cookies are set in '/' but some in other paths when I am on another page which is not '/' and i tried to set a cookie.

I tried the same for cookie-universal-nuxt

Thank you

**Comment by microcipcip** [comment]
Hi @stephenjason89. The secure cookie can only be set from Backend. Is impossible to set it when you are in client mode. So if you land to a page, the cookie is likely coming from the Backend, so the cookie is set. If you are changing page from client side, the cookie is not set because of the `secure: true` that cannot be set from Frontend for security reasons.

**Comment by stephenjason89** [comment]
@microcipcip I'm currently trying it out. But seems like after i restart my dev server visiting other pages and refreshing creates the old secure cookie.

I rebooted my laptop and it is still the same haha.

Tried it in incognito and Voila! Everything is working as it should.
Might be a cache problem with my browser hahaha. Gonna reset my cache.
