### ISSUE TITLE
cookies not readable from middleware client side

### ISSUE THREAD

**Issue by mtsbarbosa** [microcipcip/cookie-universal#23]
I have following middleware:
`export default function (context) {
process.server? console.log(context.app.$cookies.get('JSESSIONID')): console.log(this.$cookies);
}
`
On the first load, it is fine, because the middleware is loaded on server side, so I am able to retrieve the cookies
When I navigate between pages, however, middleware is executed client side and I am not able to access it either with context.app.$cookies or this.$cookies
`
console.log(context.app.$cookies) -> undefined
`
`
console.log(this.$cookies) -> app.js:304 TypeError: Cannot read property '$cookies' of undefined
`

**Comment by microcipcip** [comment]
@mtsbarbosa Are you using `cookie-universal` or `cookie-universal-nuxt`? Your example should work :/

**Comment by mtsbarbosa** [comment]
cookie-universal-nuxt
Is it wrong?

**Comment by microcipcip** [comment]
@mtsbarbosa Nothing wrong, you are using the right package. Does this work?

```
export default function (context) { 
  process.server 
    ? console.log(context.app.$cookies.get('JSESSIONID'))
    : console.log(context.app.$cookies.get('JSESSIONID'));
}
```

**Comment by mtsbarbosa** [comment]
also undefined
For your information I used nuxt generate, does it change something?

**Comment by microcipcip** [comment]
Oh yes it does, I've only tested cookie-universal with the server, my guess is that cookie universal is not initializing properly on the client side because of the nuxt generate process[ does not have `req` and `res`,](https://nuxtjs.org/api/context/) it probably goes to `isNeither` [on this line](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal/index.js#L10). 

If you are able to create and share with me a very simple project showcasing just this error, I'll try and fix it. 

You may also be able to achieve this by importing the `cookie-universal` library directly and initialize it manually (not ideal). 

For example (untested):
```
import Cookies from 'cookie-universal';
function createCookie({req, res}) {
  return Cookies(req, res);
}

export default function (context) { 
  const cookies = createCookie(context);
  process.server 
    ? console.log(cookies.get('JSESSIONID'))
    : console.log(cookies.get('JSESSIONID'));
}
```

**Comment by mtsbarbosa** [comment]
https://github.com/mtsbarbosa/vue-nuxt-cookie-example
Just -> npm run generate
then -> npm run dev

**Comment by microcipcip** [comment]
Thanks a lot, I'll have a look this evening, haven't got the time now. If you need it urgently try my fix above for now.

**Comment by mtsbarbosa** [comment]
Thanks man, I appreciate a lot your quick help! :)

**Comment by microcipcip** [comment]
@mtsbarbosa I have tried the demo but there is an error in the middleware, `this` is not available in middlewares, did you manage to fix the issue eventually?

**Comment by microcipcip** [comment]
@mtsbarbosa I am closing this since I haven't got a reply in the last 10 days, but feel free to open a new issue if you're still having this problem.
