### ISSUE TITLE
 Object doesn't support property or method 'set'

### ISSUE THREAD

**Issue by andreasohmy** [microcipcip/cookie-universal#25]
Hello, I'm having problems in IE11, it gives me the error in the title.
This is the line causing the problem:
this.$cookies.set('privacyCookie', true)

Seems to work fine in every other browser (haven't checked older than IE11 though).

I have tried updating to the latest version (2.0.14)

Any suggestions what I should do?

Thanks!

**Comment by microcipcip** [comment]
It seems that there is a problem unrelated to cookie-universal, can I see the surrounding code? Also, try to console.log the `this.$cookies` object and see if on IE11 it is outputting the right object. I think that maybe you are missing some polyfills for IE11 because I've just tested cookie-universal on IE11 console and it seems to be working all right.

**Comment by andreasohmy** [comment]
This is the surrounding code:

```
setCookie: function() {
      this.$cookies.set('privacyCookie', true)
      console.log(this.$cookies);
      let formData = new FormData();
      formData.set('consent', 'yes');

      this.$axios.post('https://myAPIUrl/consent/', formData, {withCredentials: true}).then(response => {
        console.log('Cookie consent saved')
      }).catch(function (error) {
        console.log(error);
      });
      this.cookies = true
    }
```
This is the console output:
![Screenshot 2019-04-08 at 08 56 55](https://user-images.githubusercontent.com/7402809/55704424-54afdf00-59dc-11e9-8f22-d5c83d217281.png)

What polyfills are you adding to make this work?
Thanks for replying.

**Comment by microcipcip** [comment]
@andreasohmy If IE was throwing an error from cookieUniversal you wouldn't be able to see the `console.log` since the `console.log` is after the `.set` call. I think the actual error is coming from `formData.set` which unfortunately [is not recognized by IE11](https://developer.mozilla.org/en-US/docs/Web/API/FormData/set#Browser_compatibility).

**Comment by microcipcip** [comment]
Try installing something like this: https://github.com/jimmywarting/FormData

**Comment by andreasohmy** [comment]
Oh yeah, that makes sense. I'll try to add some sort of polyfill for FormData.
Thanks a lot, and sorry!

**Comment by microcipcip** [comment]
@andreasohmy NP :)
