### ISSUE TITLE
How can I use this in Vue Hackernews-2.0 example application. 

### ISSUE THREAD

**Issue by edugrip** [microcipcip/cookie-universal#29]
For reference https://github.com/vuejs/vue-hackernews-2.0
There is no nuxt.config in this repo. It does not use nuxt. 
How can I use cookies in a server rendered application e.g. in above application. 

Please help.

**Comment by microcipcip** [comment]
@edugrip in that case you can install [cookie-universal](https://github.com/microcipcip/cookie-universal/tree/master/packages/cookie-universal) instead of cookie-universal-nuxt. I don't know that repo well, but if you want to use it only in the client you can probably have direct access like this:
```
import Cookie from 'cookie-universal';
Vue.prototype.$cookies = Cookie();
```
Then you should be able to use it with `this.$cookies.methodHere()`

Instead, if you need to read the cookie in the server it depends on the implementation, if it is an express sever you have to initialize the cookies library within app.get or app.use.

```
app.get('/', (req, res) => {
  const cookies = require('cookie-universal')(req, res);
})
```
Then you should be able to use it with `cookies.methodHere()`

**Comment by microcipcip** [comment]
@edugrip  I am closing this issue as I am not receiving any feedback. Let me know if you are still experiencing this error.
