### ISSUE TITLE
Avoid implicit JSON?

### ISSUE THREAD

**Issue by frankier** [microcipcip/cookie-universal#3]
In get(...) there is the following code:

      try {
        return JSON.parse(cookie)
      } catch(err) {
        return cookie
      }

This code is likely to cause bugs for the following reasons

1. Users can modify cookies. This means a malicious user can change their cookie to be a JSON string and now a method that I expect to return a string returns and object. This isn't a security problem on its own, but it seems like the sort of thing that when combined with something else could get the program to go down unindented path.
2. It's an ``in-band'' encoding which collides with strings I might want to store. I can test my program a lot, and not put anything that's valid JSON in my cookies, but then I accidentally put a string which is valid JSON in my cookie. Now when it gets decoded my program behaves in an unintended way, because it's dealing with a value other than a string.

**Comment by microcipcip** [comment]
Thank you for the feedback @frankier, it makes perfect sense! To avoid breaking changes I suggest adding a property to disable this behaviour. Maybe something like this?

```
const cookies = Cookie()
cookies.parseJSON = false
```

Another possibility would be to pass an object to `get` and `getAll` and set it in the instance, so this would allow you to override the global setting done on initialization: 
```
cookies.get('cookie-name', { parseJSON: false  })
```

Because of the way I set up the `get` function (the second argument is a boolean, I should have used an object) I will have to do a breaking change and have to move the script to v2.0, which is something I was already thinking about to keep the API consistent.

**Comment by microcipcip** [comment]
@frankier try to install the 2.0 version, with it you have several ways to disable parseJSON.
