### ISSUE TITLE
is there any changelog ?

### ISSUE THREAD

**Issue by jd1378** [microcipcip/cookie-universal#62]
Hi
I've been updating one of my project's recently and I was wondering if there's a changelog kept anywhere (or I couldn't find it) ? I find it useful when updating a project dependencies to see what they have fixed and what new features they got
thank you again for this great module

**Comment by microcipcip** [comment]
Hi @jd1378, unfortunately there is no changelog. Had I built this project today I would have used [semantic release](https://github.com/semantic-release/semantic-release) which does it automatically.

Anyway the risk of breaking something is rather slim since I am mostly doing Typescript updates and keeping it retro compatible. The biggest change I've done lately [was allowing the removal of a cookie with a falsy value, which was a bug](https://github.com/microcipcip/cookie-universal/commit/948b7e1eca6293b98182310a08aaa766fae7f480).

**Comment by jd1378** [comment]
Hi
thanks for the reply
I understand now
