### ISSUE TITLE
Cannot read property '$cookies' of undefined

### ISSUE THREAD

**Issue by Manouher** [microcipcip/cookie-universal#67]
Hello everyone, I'm new to nuxt, I can't resolve this error, someone can help me,
> `TypeError :`
Cannot read property '$cookies' of undefined

> `nuxt.config.js`

```javascript
 modules: [
    '@nuxtjs/axios',
    '@nuxtjs/dotenv',
    'cookie-universal-nuxt',
  ],

```

> `store/pages/state.js`
```javascript
export default () => ({
  user_conf: this.$cookies.get('config-app'),
})
```

**Comment by microcipcip** [comment]
@Manouher I am not sure you are using the library properly, Vue `store.state` should be pure. Usually you would be reading the cookies in the `store.actions` or in any vue mounted state, or in a module middleware.

Also the `this` keyword is probably undefined in that case, __you should avoid using the arrow functions with `this` keyword__  because in a arrow function 'this' refers to it's current surrounding scope and no further, which may be give you unexpected resulsts most of the time.
